# Changing this file necessitates a server restart
name: "NeuroLibre"
abbreviation: "NeuroLibre"
issn: ""
tagline: "a preprint server for <strong>interactive</strong> data analyses."
logo_url: "https://conp-pcno.github.io/images/neurolibre-icon-red.png"
url: "http://neurolibre.herokuapp.com"
editor_email: "editors@neurolibre.org"
noreply_email: "noreply@neurolibre.org"
twitter: "@NeuroLibre"
google_analytics: ""
github: "neurolibre/neurolibre"
reviews: "neurolibre/neurolibre-reviews"
papers_html_url: "https://neurolibre.herokuapp.com/papers/"
papers_repo: "neurolibre/neurolibre-papers"
product: "notebooks" # the *thing* being submitted for review
reviewers: "https://tinyurl.com/y22xx6ux"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the NeuroLibre submission criteria.
paper_types: []
